project_id = "zhhagwrgufwamqvjaoip"

[functions.fetch-stock-price]
verify_jwt = false

[functions.update-prices]
verify_jwt = false

[functions.fetch-options-chain]
verify_jwt = false

[functions.fetch-historical-volatility]
verify_jwt = false

[functions.fetch-stock-data]
verify_jwt = false

[functions.fetch-fred-data]
verify_jwt = false

[functions.check-thesis-alerts]
verify_jwt = false