import phase1 from './evidence/phase1-results.json';
import phase4 from './evidence/phase4-results.json';
import { validationStatus } from './compare';
import type { ModelValidationPlan, ValidationResult } from './types';

const NOT_FITTED = 'Estimator with no parameters fitted to data (fixed formula / fixed λ), so there is no in-sample fit to test out of sample. Forecast-quality OOS evaluation belongs to VOL-005.';

/** Validation plans: which evidence closes each model. Unit tests run in CI (Vitest) for every model listed. */
export const VALIDATION_PLANS: ModelValidationPlan[] = [
  { modelId: 'DAT-001', required: ['unit', 'independent-benchmark'], notes: ['Live Yahoo download not reproducible offline; requires a recorded snapshot compared against a second free source.'] },
  { modelId: 'DAT-002', required: ['numerical', 'independent-benchmark'], notApplicable: { 'out-of-sample': 'Deterministic data transformation.' } },
  { modelId: 'DAT-003', required: ['numerical', 'independent-benchmark'], notApplicable: { 'out-of-sample': 'Deterministic data transformation.' } },
  { modelId: 'STA-001', required: ['numerical', 'independent-benchmark'], notApplicable: { 'out-of-sample': 'Descriptive statistics, no fitted parameters.' } },
  { modelId: 'VOL-001', required: ['numerical', 'independent-benchmark'], notApplicable: { 'out-of-sample': NOT_FITTED } },
  { modelId: 'VOL-002', required: ['numerical', 'independent-benchmark'], notApplicable: { 'out-of-sample': NOT_FITTED } },
  { modelId: 'COR-001', required: ['numerical', 'independent-benchmark'], notApplicable: { 'out-of-sample': 'Sample estimator with no fitted parameters; out-of-sample covariance forecast quality is evaluated with COR-004 / POR-001.' } },
  { modelId: 'COR-002', required: ['numerical', 'independent-benchmark'], notApplicable: { 'out-of-sample': 'Deterministic transform of COR-001.' } },
];

/** Recorded evidence (generated by `bun validation/run-phase*.ts`). */
export const VALIDATION_RESULTS = [...phase1, ...phase4] as ValidationResult[];

export const resultsFor = (modelId: string) => VALIDATION_RESULTS.filter((r) => r.modelId === modelId);
export const planFor = (modelId: string) => VALIDATION_PLANS.find((p) => p.modelId === modelId);
/**
 * Status of the VALIDATION LAYER only (derived from recorded evidence) — not the
 * item's overall progress status, which lives in the matrix (src/lib/quant-matrix).
 * E.g. DAT-001: overall IN PROGRESS, validation layer NOT STARTED.
 */
export const validationStatusFor = (modelId: string) => {
  const p = planFor(modelId);
  return p ? validationStatus(p, VALIDATION_RESULTS) : 'NOT STARTED';
};
